spring.application.name=st-domain-redirector

# ??? ?? ?? (??)
server.forward-headers-strategy=framework

# ?? 8080? ?? (Nginx? 443 ??)
server.port=8080
server.ssl.enabled=false

# ??? ?? SSL/???? ?? ??? ?? ?? ?? ?? ??
# server.ssl.key-store-type=PKCS12
# server.ssl.key-store=/etc/letsencrypt/live/st-research.co.kr/keystore.p12
# server.ssl.key-store-password=...
# server.ssl.key-alias=tomcat
